version: '3.8'

services:
  app:
    build:
      context: .
      target: production
      args:
        APP_ENV: production
    ports:
      - "3000:3000"
    environment:
      RUN_MIGRATIONS: "true"
    env_file:
      - .env.production
    volume:
      - /volume1/docker/data:/app/data