version: '3.8'

services:
  app:
    build:
      context: .
      args:
        APP_ENV: local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: bun run dev
    env_file:
      - .env.local
      - prisma/.env
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-dev-data: