import { Role, Disposisi, Status, AksesArsip, DispLanjutan } from '../utils/db.server';

export type User = {
  id: string,
  email: string,
  name: string,
  username: string,
  bidang: Disposisi | null,
  password?: string,
  role?: Role,
  address: string | null,
  phone_number: bigint | null
}

export type DataSurat = {
  id: string,
  nomor_urut: number,
  nama_surat: string,
  tanggal_diterima: Date,
  tanggal_surat: Date,
  kode: string,
  no_agenda: string,
  no_surat: string,
  hal: string,
  tanggal_waktu: Date,
  tempat: string,
  disposisi: Disposisi,
  index: string | null,
  pengolah: string,
  sifat: string | null,
  link_scan: string | null,
  disp_1: Date,
  disp_2: Date,
  disp_3: Date | null,
  disp_4 : Date | null,
  disp_1_notes: string | null,
  disp_2_notes: string | null,
  disp_3_notes: string | null,
  disp_4_notes: string | null,
  disp_lanjut: DispLanjutan | null,
  tindak_lanjut_1: Date | null,
  tindak_lanjut_2: Date | null,
  tl_notes_1: String | null,
  tl_notes_2: String | null,
  status: Status | null,
  dok_final: string | null,
  dok_dikirim: Date | null,
  tanda_terima: Date | null,
  timestamp: Date
}

export type SuratKeluar = {
  id: string,
  nomor_urut: number,
  kode: string,
  klasifikasi: string,
  no_register: string,
  tujuan_surat: string | null,
  perihal: string,
  tanggal_surat: Date,
  akses_arsip: AksesArsip,
  pengolah: Disposisi,
  pembuat: string | null,
  catatan: string | null,
  link_surat: string | null,
  koreksi_1: string | null,
  koreksi_2: string | null,
  status: Status | null,
  timestamp: Date
}